mongo_config:
  db_name: "MTSDB"
  conn_string: "mongodb+srv://%s:%s@mtscluster.tl4ppgr.mongodb.net/?retryWrites=true&w=majority"
  collections:
    user: "User"
    certificate: "Certificate"
    category: "Category"
    service: "Service"
